@startuml WorkFlow

title
    <u>SingleJob 동작과정</u>
    ====<size:14>첫 시퀀스 다이어그램이라 매우 간략화시킴</size>
    그리기 넘 어렵다

end title

participant 메인쓰레드 [
    <size:14><b>메인쓰레드</b></size>
]

participant 외부싱글쓰레드 [
    <size:14><b>외부싱글쓰레드</b></size>
    ----
    <size:12>이미지 목록을 처리하기위해</size>
    <size:12>동작하는 외부 쓰레드</size>
]
participant 이미지목록

메인쓰레드 -> 외부싱글쓰레드: 이미지 처리작업 요청
외부싱글쓰레드 ->> 이미지목록 : 처리작업 진행
외부싱글쓰레드 ->> 이미지목록 : 처리작업 진행
외부싱글쓰레드 ->> 이미지목록 : 처리작업 진행
외부싱글쓰레드 ->> 이미지목록 : 처리작업 진행 (이미지 수 만큼)
외부싱글쓰레드 -> 메인쓰레드 : 작업처리 완료 통보




@enduml